config/routes.rb
Froshulator::Application.routes.draw do
  get "compare", to: "compare#index"
  get "compare/list"
  get "compare/delete/:id", to: "compare#delete"
  get "compare/compare/:left/:right", to: "compare#compare"
  get "compare/savecmp/:loser/:winner", to: "compare#savecmp"

  resources :presort do
  end
  get "slorg", to: "presort#table"
  get "presort/apply_cutoffs/:green/:blue", to: "presort#apply_cutoffs"

  resources :froshes do
    get :comments, to: :comments
    put :comments, to: :save_comments
    resources :votes
  end

  get "froshes/mass_vote/:meal", to: "froshes#mass_vote"
  post "froshes/mass_vote/frosh_votes", to: "froshes#save_mass"

  get "froshes/dinner/:meal", to: "froshes#dinner"

end

app/controllers/presort_controller.rb
class PresortController < ApplicationController
    def index
        @froshes = Frosh.ordered
        @positions = []
        @froshes.each_index do |idx|
            @positions.push([(idx + 1).to_s , @froshes[idx].id])
        end
    end
    
    def table
        @froshes = Frosh.ordered
        @positions = []
        @froshes.each_index do |idx|
            @positions.push([idx.to_s + "-" + @froshes[idx].name, @froshes[idx].id])
        end
    end

    def update
        frosh = Frosh.find(params[:id])
        old_frosh = Frosh.find(params[:frosh][:prelim_rank])
        frosh.list = old_frosh.list
        frosh.save
        if frosh != old_frosh.previous
            if old_frosh.first?
                frosh.prepend
            else
                frosh.append_to old_frosh.previous
            end
        end
        #somehow update the ranking somehow
        redirect_to presort_index_path
    end

    def new
        froshes = Frosh.all
        #sort the array by the prelim score
        froshes.sort! { |b, a| a.prelim_score <=> b.prelim_score }
        prev = false
        froshes.each do |frosh|
            if prev
                frosh.append_to prev
                prev = frosh
            else
                frosh.update_attribute(:first, true)
                prev = frosh
            end
        end
        redirect_to presort_index_path
    end

    def apply_cutoffs
        green = params[:green].to_i
        blue = params[:blue].to_i
        froshes = Frosh.ordered
        froshes.each_index do |index|
            if index < green
                froshes[index].list = 0
            elsif index < blue
                froshes[index].list = 1
            else
                froshes[index].list = 2
            end
            froshes[index].save
        end
        redirect_to presort_index_path
    end
end

app/helpers/presort_helper.rb
module PresortHelper
end

app/views/presort/index.html.erb
<div id="presort">

<div id="froshtable">
<!-- A table of froshes. Please generate them yourself. As long as they're in this format, it should be fine. -->
<!-- Just copy and paste this div. Each td is a frosh box. They should organize themselves.-->
<% @froshes.each_index do |frosh_index| %>
    <% frosh = @froshes[frosh_index] %>
    <%= content_tag "div", class: frosh.color do %><!-- replace "green" with "blue" or "red" for froshes in other lists-->
	    <%= frosh_index + 1 %><br> <!-- replace with frosh's current ranking, compared to all the froshes. 1 = bestfrosh, 2 = not-as-good-frosh, etc-->
	    <%= image_tag frosh.image_url %><br> <!-- replace with actual photo of frosh -->
        <h3><%= frosh.name %> <%= "(" + frosh.nickname + ")" unless frosh.nickname == nil or frosh.nickname == "" %></h3>
	    <%= frosh.anagram %><br>
	    Stdev: <%= number_with_precision(frosh.stdev) %><br> <!-- replace with actual rating -->
	    Mean:  <%= number_with_precision(frosh.mean) %><br> <!-- replace with actual rating -->
	    Number of votes: <%= frosh.percent_voted %><br> <!-- replace with actual percentage -->
        <%= link_to "comments", frosh_comments_path(frosh) %><br>
        <%= form_for frosh, url: presort_url(frosh), method: :put do |f| %>
            <%= f.select :prelim_rank, @positions %>
            <%= f.submit "insert rank"%>
        <% end %>
        <table>
        <tr><td>
        <% if(frosh_index > 15) %>
          <%= form_for frosh, url: presort_url(frosh), method: :put do |f| %>
              <%= f.hidden_field :prelim_rank, value: @positions[frosh_index - 15][1] %>
              <%= f.submit "up 15"%>
          <% end %>
        <% end %>
        </td><td>
        <% if(frosh_index < @froshes.length - 15) %>
          <%= form_for frosh, url: presort_url(frosh), method: :put do |f| %>
              <%= f.hidden_field :prelim_rank, value: @positions[frosh_index + 15][1] %>
              <%= f.submit "down 15"%>
          <% end %>
        <% end %>
        </td></tr></table>
	<% end %>
<% end %>
<br>
<div id="filters">
<!-- IDK what you wanna do with these buttons. Just slap them in a row with some separators and call it good enough -->
<form>
<input type="button" value="Sort by Rating"> 
||| Filters: 
<input type="checkbox" name="filter" value="filter1">filter 1
<input type="checkbox" name="filter" value="filter2">filter 2
<input type="checkbox" name="filter" value="filter3">filter 3
<input type="button" value="Filter by something"> 
</form>
</div>

</div>

app/views/presort/table.html.erb
<div id="presort">

<div id="froshtable">
<!-- A table of froshes. Please generate them yourself. As long as they're in this format, it should be fine. -->
<!-- Just copy and paste this div. Each td is a frosh box. They should organize themselves.-->
<table>
<% @froshes.each_index do |frosh_index| %>
    <tr>
    <% frosh = @froshes[frosh_index] %>
	    <td><%= frosh_index + 1 %></td>
	    <td><%= frosh.name %></td>
	    <td><%= frosh.prelim_score %></td>
	    <td><%= frosh.stdev %></td>
	    <td><%= frosh.mean %></td>
	    <td><%= frosh.percent_voted %></td>
    </tr>
<% end %>
</table>
<div id="filters">
<!-- IDK what you wanna do with these buttons. Just slap them in a row with some separators and call it good enough -->
<form>
<input type="button" value="Sort by Rating"> 
||| Filters: 
<input type="checkbox" name="filter" value="filter1">filter 1
<input type="checkbox" name="filter" value="filter2">filter 2
<input type="checkbox" name="filter" value="filter3">filter 3
<input type="button" value="Filter by something"> 
</form>
</div>

</div>