config/routes.rb
Froshulator::Application.routes.draw do
  get "compare", to: "compare#index"
  get "compare/list"
  get "compare/delete/:id", to: "compare#delete"
  get "compare/compare/:left/:right", to: "compare#compare"
  get "compare/savecmp/:loser/:winner", to: "compare#savecmp"

  resources :presort do
  end
  get "slorg", to: "presort#table"
  get "presort/apply_cutoffs/:green/:blue", to: "presort#apply_cutoffs"

  resources :froshes do
    get :comments, to: :comments
    put :comments, to: :save_comments
    resources :votes
  end

  get "froshes/mass_vote/:meal", to: "froshes#mass_vote"
  post "froshes/mass_vote/frosh_votes", to: "froshes#save_mass"

  get "froshes/dinner/:meal", to: "froshes#dinner"

end

app/models/frosh.rb
class Frosh < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  resort!
  # attr_accessible :title, :body
  has_many :votes

  has_many :won_compares, class_name: :Comparison, foreign_key: :winner_id, dependent: :destroy
  has_many :lost_compares, class_name: :Comparison, foreign_key: :loser_id, dependent: :destroy

  def prelim_score
    if(votes.length == 0)
      return -1
    else
      #average = ( votes.map(&:value).inject{ |sum, x| sum + x } || 0 ).to_f / (votes.length + 1)
      score = (mean * votes.length.to_f + art_votes * 2.5) / (votes.length.to_f + art_votes)
      
      score += -0.2 * stdev_adj
      
      #if(mean > 3.0)
      #  exp_factor = 1.0 / (1.0 + Math.exp(-3.0 * (mean - 4.0)))
      #  score += exp_factor * 1.3 * votes.length.to_f / 9
        # TODO
      #  score -= exp_factor * 0.25 * stdev / 3
      #else
      #  exp_factor = 1.0 - 1.0 / (1.0 + Math.exp(-3.0 * (mean - 2.0)))
      #  score -= exp_factor * 1.3 * votes.length.to_f / 9
      #  # TODO
      #  score += exp_factor * 0.25 * stdev / 3
      #end
    end
    puts score
    return score
  end

  def dinner_name_slorg
    #return "wow"
    #puts dinner
    return ['Wednesday/Alice', 'Thursday/Space', 'Friday/Navy', 'Saturday 1/Pirates', 'Saturday 2/Crooners', 'Sunday/Bureaucracy', 'Monday/Crackpot', 'Pretentious'][dinner - 1]
  end

  def color
    @color ||= ["green", "blue", "red"][list] if list
  end

  def percent_voted
    #change this depending on max number of votes
    #TODO using a helper here is bad or whatever blah blah blah
    #@percent_voted ||= number_to_percentage(votes.length * 3.224131, precision: 1)
    @percent_voted ||= votes.length
  end

  def mean
    votes_copy = votes.map(&:value)
    @mean ||= votes_copy.inject(0) { |sum, x| sum += x } / votes_copy.size.to_f
  end

  def stdev_adj
    
    votes_copy = votes.map(&:value)
    for i in 1..art_votes
        votes_copy.push(2.5)
    end

    if(votes.length > 1)
      @stdev = Math.sqrt(votes_copy.inject(0) { |variance, x| variance += (x - mean) ** 2 } / (votes.length - 1 + art_votes))
    else
      0
    end
  end
  
  def stdev
    votes_copy = votes.map(&:value)
    #votes_copy.push(2.5)
    #votes_copy.push(2.5)
    #votes_copy.push(2.5)
    if(votes.length > 1)
      @stdev = Math.sqrt(votes_copy.inject(0) { |variance, x| variance += (x - mean) ** 2 } / (votes.length - 1))
    else
      0
    end
  end

  def art_votes
    3
  end

  def dinner_name
  end
end

app/controllers/froshes_controller.rb
class FroshesController < ApplicationController
  def new
  end

  def create
  	@frosh = Frosh.new
    #TODO use mass assignment if desired
	@frosh.name = params[:froshform][:name]
    if params[:froshform][:last_name] == ""
      @frosh.last_name = params[:froshform][:name].split(" ")[-1]
    else
      @frosh.last_name = params[:froshform][:last_name]
    end
	@frosh.dinner = params[:froshform][:dinner]
	@frosh.dessert = params[:froshform][:dessert]
	@frosh.image_url = params[:froshform][:image_url]
    if @frosh.image_url == ""
        @frosh.image_url = "noimg.png"
    end
	@frosh.anagram = params[:froshform][:anagram]
	@frosh.interest_url = params[:froshform][:interest_url]
    @frosh.male = params[:froshform][:male]
	@frosh.save
	redirect_to froshes_path
  end

  def update
  	@frosh = Frosh.find(params[:id])
	@frosh.name = params[:frosh][:name]
	@frosh.last_name = params[:frosh][:last_name]
	@frosh.dinner = params[:frosh][:dinner]
	@frosh.dessert = params[:frosh][:dessert]
	@frosh.image_url = params[:frosh][:image_url]
	@frosh.anagram = params[:frosh][:anagram]
	@frosh.interest_url = params[:frosh][:interest_url]
    @frosh.male = params[:frosh][:male]
	@frosh.save
	redirect_to froshes_path
  end

  def show
  	@frosh = Frosh.find(params[:id])
  end

  def edit
  	@frosh = Frosh.find(params[:id])
  end
  
  def comments
  	@frosh = Frosh.find(params[:frosh_id])
  end

  def save_comments
  	@frosh = Frosh.find(params[:frosh_id])
    @frosh.comments = params[:frosh][:comments]
    @frosh.nickname = params[:frosh][:nickname]
	@frosh.save
	#redirect_to froshes_path
    render text: 'saved'
  end

  def destroy
    Frosh.find(params[:id]).destroy
    redirect_to froshes_path
  end

  def index
  	@froshes = Frosh.all
  end

  def mass_vote
    @froshes = Frosh.where(dinner: params[:meal])
  end
  
  def dinner
    @froshes = Frosh.where(dinner: params[:meal])
  end

  def save_mass
    params['mass_vote'].each do |mass_vote|
        frosh = Frosh.find(mass_vote['frosh_id'])
        mass_vote['votes'].split('').each do |character|
            frosh.votes.create(value: character.to_i)
            #vote.value = character.to_i
            #vote.save
        end
    end
    render text: params.inspect
    #redirect_to froshes_path
  end
end

app/helpers/froshes_helper.rb
module FroshesHelper
end

app/views/froshes/comments.html.erb
<div id="container">

    <div id="frosh-info">
       <h2><%= @frosh.name %></h2>
	   <h3><%= @frosh.anagram %></h3>
	   <h3><%= link_to 'interest sheet', @frosh.interest_url %></h3>
	   <%= image_tag @frosh.image_url %>
	</div>
	    
	<div id="comment-box">
	   Comments:<br>
       <%= form_for @frosh, url: frosh_comments_url(@frosh), method: :put do |f| %>
	      <!-- input javascript or something to make this form actually do things-->
          <%= f.text_area :comments, rows: 30, cols: 65 %>
		  <br>
          <%= f.text_field :nickname %>
		  <br>
          <%= f.submit "Save Comments"%>
       <% end %>
    </div>
</div>

app/views/froshes/dinner.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<link href="styles/comments.css" rel="stylesheet" type="text/css">
</head>

<body>
<div id="list-container">
    <% @froshes.each do |frosh| %>
    <div id="edit-frosh">
        <%= image_tag frosh.image_url %>
        <div id="frosh-links">
        <%= frosh.name %> <br>
        <%= frosh.nickname %> <br>
        <%= frosh.anagram %> <br>
        <%= link_to "comments", frosh_comments_path(frosh) %>
        </div>
    </div>
    
    <% end %>
    
</div>
</body>

</html>

app/views/froshes/edit.html.erb
Edit this frosh's data
<%= form_for @frosh, url: frosh_path(@frosh), method: :put do |f| %>
name
<%= f.text_field :name %>
last name
<%= f.text_field :last_name %>
dinner
<%= f.text_field :dinner %>
dessert
<%= f.text_field :dessert %>
image url
<%= f.text_field :image_url %>
anagram
<%= f.text_field :anagram%>
interest url
<%= f.text_field :interest_url%>
male?
<%= f.check_box :male %>
<%= f.submit %>
<% end %>

app/views/froshes/index.html.erb
<table class="sortableTable">
<tr class="tableHead"><td></td><td>Name</td><td>Last name</td><td>nickname</td><td>Dinner</td><td>dessert</td><td>anagram</td><td>male?</td></tr>
<% @froshes.each do |frosh| %>
<tr class="tableRow">
    <!-- hack hack hack andrew fix this plz -->
    <!-- though I guess it works... -->
    <td class="list-image">
        <div id="frosh-info">
            <%= image_tag frosh.image_url %>
        </div>
    </td>
	<td><%= frosh.name %></td>
	<td><%= frosh.last_name %></td>
	<td><%= frosh.nickname %></td>
	<td><%= frosh.dinner %></td>
	<td><%= frosh.dessert %></td>
	<td><%= frosh.anagram %></td>
	<td><%= frosh.male %></td>
    <td><%= link_to "votes", frosh_votes_path(frosh) %></td>
    <td><%= link_to "view", frosh_path(frosh) %></td>
    <td><%= link_to "edit", edit_frosh_path(frosh) %></td>
    <td><%= link_to "comments", frosh_comments_path(frosh) %></td>
    <td><%= link_to "destroy", frosh_path(frosh), method: :delete%></td>
</tr>
<% end %>
</table>

app/views/froshes/mass_vote.html.erb
<%= form_tag 'frosh_votes' do %>
    <% @froshes.each do |frosh| %>
        <%= frosh.name %>
        <%= text_field_tag 'mass_vote[][votes]' %>
        <%= hidden_field_tag 'mass_vote[][frosh_id]', frosh.id %>
        <br>
    <% end %>
    <%= submit_tag %>
<% end %>

app/views/froshes/new.html.erb
Create a new frosh
<%= form_for :froshform, url: froshes_path do |f| %>
name
<%= f.text_field :name %>
last name (leave blank if their name is normal)
<%= f.text_field :last_name %>
dinner
<%= f.text_field :dinner %>
dessert
<%= f.text_field :dessert %>
image url
<%= f.text_field :image_url %>
anagram
<%= f.text_field :anagram%>
interest url
<%= f.text_field :interest_url%>
male?
<%= f.check_box :male %>
<%= f.submit %>
<% end %>

app/views/froshes/show.html.erb
<%= @frosh.name %>
<%= @frosh.dinner %>